### ISSUE TITLE
NPE when running a job with 'Pipeline As Yaml from SCM'

### ISSUE THREAD

**Issue by maxenceledore** [jenkinsci/pipeline-as-yaml-plugin#35]
The problem only occurs while running a job with 'Pipeline As Yaml from SCM'. What follows is the Output console content :

```
java.lang.NullPointerException
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.<init>(CpsScmFlowDefinition.java:78)
	at org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.cps.PipelineCpsScmFlowDefinition.<init>(PipelineCpsScmFlowDefinition.java:30)
	at org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.PipelineAsYamlScmFlowDefinition.create(PipelineAsYamlScmFlowDefinition.java:73)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Finished: FAILURE
```

1. Create a new job
2. Setup the pipeline section with 'Pipeline As Yaml from SCM' and feed it with SCM/repo/credentials/branch.
3. Click Save
4. Running the job lead to a fail wih NPE

**Expected behavior**
A healthy job execution.

Versions:

- Jenkins Version : 2.249.2
- Plugin Version : 0.12-rc

Context:
It may be related to this issue : https://github.com/jenkinsci/pipeline-as-yaml-plugin/issues/34

**Comment by aytuncbeken** [comment]
Hi Again,

yes it is related to previous issue which you had opened. This will be fixed too with the new version.

**Comment by aytuncbeken** [comment]
Release with 0.14-rc
