### ISSUE TITLE
SnakeYAML method not found

### ISSUE THREAD

**Issue by xdxiaodong** [jenkinsci/pipeline-as-yaml-plugin#76]
SnakeYAML API Plugin 2.2-111.vc6598e30cc65
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
	at io.jenkins.plugins.pipeline.parsers.AbstractParser.<init>(AbstractParser.java:25)
	at io.jenkins.plugins.pipeline.parsers.PipelineParser.<init>(PipelineParser.java:26)
	at io.jenkins.plugins.pipeline.cps.PipelineCpsScmFlowDefinition.create(PipelineCpsScmFlowDefinition.java:50)
	at io.jenkins.plugins.pipeline.PipelineAsYamlScmFlowDefinition.create(PipelineAsYamlScmFlowDefinition.java:74)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:311)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)

**Comment by Moneykicks101001** [comment]
i have the same issue, which jenkins version you currently use @xdxiaodong

**Comment by chihabam** [comment]
Same issue here, any luck?

**Comment by jonesbusy** [comment]
Jenkins core and plugins are now depending on SnakeYAML 2: https://plugins.jenkins.io/snakeyaml-api/

Plugin need to be adapted and refreshed

**Comment by slide** [comment]
I believe this has been resolved via the PR above. Please reopen if it is still an issue.
